# -*- coding: utf-8 -*-
"""Powell Smiles E-(Python Internals).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gS4jZJoyLxu_7CkQujDiHIbL1723GkiX
"""

#i)print paragraph
print(""" I am signing up for Replit's 100 days of Python challenge! I will make sure to spent 
some time every day coding along, for a minimum of 10 minutes a day.ll be using 
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field """)

#ii)dictionry for malware and desctription(MANIPULATION)
mal_dict={'self replicating':'virus','hidden effects':'trojan horse','spreads faster':'worm',
          'basedon trigger event':'logic bomb','server atack':'root kit','ROGUE AP':'worm hole'}
#add a key and value to dictionary
mal_dict['back door']='hidden listener'
mal_dict
#remove a key and value from the dictionary
del(mal_dict['self replicating'])
mal_dict
type(mal_dict) # to print the type of data structure
len(mal_dict)
#update the value of KEY
mal_dict['Rogue Ap']='BLack Hole'
mal_dict

#2)Calculate Net Price and GST amount of the mobile.
price=int(input("Enter the price of the mobile phone: "))
gst_per=int(input("Enter the gst percent: "))
gst_amt=(price*gst_per)/100
print("The GST Amount Is : " ,gst_amt)
Net_price=price+gst_amt
print("The Net Price is: ", Net_price)

#3)datasets for IPC Sections

import pandas as pd
police_rd=pd.DataFrame(
    {"Offence":["phishing through whatsapp","forgery of electronic records","false information","scareware through mail apps","unwanted facebook dm","false information"],
     "IPC Section":[420 ,463 ,420,523,420,244],
     "penalities":["2 YEARS","6 MONTHS","1 YEAR", "6 MONTHS",'1 YEAR','2 MONTHS']}
)
police_rd['Category']=police_rd["IPC Section"].apply(lambda x: "Whatsapp/twitter/facebook" if x==420 else "cyber space crime" )

display(police_rd)

#name, age, dob, weight and height.
import pandas as pd
deets=pd.DataFrame(
    {'NAme':['arun','powell','smiles','sam','ram','king','joe','rupert','kisngst','samuel'],
             'age':[21,20,21,19,20,18,19,20,19,21],
     'dob':["1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000","1.03.2000"],
     'weight':[45,54,55,43,42,46,47,48,49,50],
     'height':[145,153,155,156,157,158,159,146,155,157]}
)
deets['bmi']=(deets['weight'])/(deets['height']*2*0.01)
deets['Health Status']=deets['bmi'].apply(lambda x: "not healthy" if x<=19.0 else "Healthy")
display(deets)

#5)house hold Electricity Bill
amount=int(input("Enter The Consumed amount of unit: "))
if amount<=100:
  bill_amount=0.50*amount
  print("The Bill Amount Is :",bill_amount)

elif amount in range(101,200):
  bill_amount=0.75*amount
  print("The Bill Amount Is :",bill_amount)
elif amount in range(201,300):
  bill_amount=1.20*amount
  print("The Bill Amount Is :",bill_amount)
elif amount>300:
  bill_amount=1.50*amount
  print("The Bill Amount Is :",bill_amount)
else:
  print("Enter A valid Input: ")

